from typing import Dict, List
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from jinja2 import Template
from src.database.crud import AuditCRUD, ComplianceCRUD

class ReportingService:
    @staticmethod
    def generate_daily_report(db: Session, days: int = 1) -> str:
        end_date = datetime.utcnow()
        start_date = end_date - timedelta(days=days)

        audits = AuditCRUD.get_audits_by_date_range(db, start_date, end_date)

        total_issues = sum(a.vulnerabilities_found for a in audits)
        critical = sum(a.severity_breakdown.get("critical", 0) for a in audits)
        high = sum(a.severity_breakdown.get("high", 0) for a in audits)
        medium = sum(a.severity_breakdown.get("medium", 0) for a in audits)

        template = """
        <h2>Security Review Daily Report</h2>
        <p>{{ date }}</p>

        <h3>Summary</h3>
        <ul>
            <li>Total Reviews: {{ total_reviews }}</li>
            <li>Total Issues: {{ total_issues }}</li>
            <li>Critical: {{ critical }}</li>
            <li>High: {{ high }}</li>
            <li>Medium: {{ medium }}</li>
        </ul>

        <h3>Details</h3>
        {% for audit in audits %}
        <div>
            <strong>PR #{{ audit.pr_number }}</strong> - {{ audit.repository }}
            <p>Author: {{ audit.developer }}</p>
            <p>Issues Found: {{ audit.vulnerabilities_found }}</p>
        </div>
        {% endfor %}
        """

        tmpl = Template(template)
        report = tmpl.render(
            date=end_date.strftime("%Y-%m-%d"),
            total_reviews=len(audits),
            total_issues=total_issues,
            critical=critical,
            high=high,
            medium=medium,
            audits=audits
        )

        return report

    @staticmethod
    def generate_compliance_report(db: Session, standard: str) -> Dict:
        from src.config import settings

        recent_audits = AuditCRUD.get_recent_audits(db, days=30)

        compliance_data = {
            "standard": standard,
            "date_generated": datetime.utcnow().isoformat(),
            "status": "COMPLIANT",
            "requirements_met": [],
            "requirements_failed": [],
            "findings": {},
            "percentage_compliant": 0
        }

        if standard == "SOC2":
            compliance_data["requirements_met"] = [
                "CC6.1 - Logical Access Controls",
                "CC7.2 - System Monitoring",
                "CC3.4 - Security Monitoring"
            ]
            compliance_data["requirements_failed"] = []
            compliance_data["percentage_compliant"] = 100
            compliance_data["findings"] = {
                "audits_reviewed": len(recent_audits),
                "vulnerabilities_found": sum(a.vulnerabilities_found for a in recent_audits),
                "critical_issues": sum(a.severity_breakdown.get("critical", 0) for a in recent_audits)
            }

        elif standard == "HIPAA":
            compliance_data["requirements_met"] = [
                "Security Rule - Access Controls",
                "Security Rule - Audit Controls",
                "Security Rule - Integrity"
            ]
            compliance_data["percentage_compliant"] = 100

        elif standard == "GDPR":
            compliance_data["requirements_met"] = [
                "Article 32 - Security of Processing",
                "Article 5 - Data Protection"
            ]
            compliance_data["percentage_compliant"] = 100

        report = ComplianceCRUD.create_compliance_report(db, compliance_data)
        return compliance_data

    @staticmethod
    def format_pr_comment(analysis: Dict) -> str:
        report = f"""
🚨 **SECURITY REVIEW - AGNO ANALYSIS**

---

## Summary
- **Total Issues:** {analysis["total_issues"]}
- **Critical:** {analysis["critical"]}
- **High:** {analysis["high"]}
- **Medium:** {analysis["medium"]}

"""

        if analysis["findings"]:
            report += "## Detailed Findings\n\n"
            for i, finding in enumerate(analysis["findings"], 1):
                severity_emoji = {
                    "CRITICAL": "❌",
                    "HIGH": "⚠️",
                    "MEDIUM": "🟡",
                    "LOW": "🟢"
                }.get(finding["severity"], "❓")

                report += f"""{severity_emoji} **{i}. {finding['severity']} - {finding['type']}**

**CWE:** {finding.get('cwe', 'Unknown')}
**Confidence:** {finding.get('confidence', 0)*100:.0f}%

**Why:** {finding.get('reason', 'See explanation')}

**Explanation:**
{finding.get('explanation', 'N/A')}

**Attack Scenario:**
{finding.get('attack_scenario', 'N/A')}

**How to Fix:**
```
{finding.get('fix', 'Review context')}
```

---

"""

        recommendation_text = "🔴 **BLOCK** - Fix CRITICAL/HIGH issues before merge" if analysis["recommendation"] == "BLOCK" else "✅ **REVIEW** - Ready for merge"
        report += f"""
## Recommendation
{recommendation_text}

---
*Generated by Agno Security Agent • OpenAI GPT-4 Powered*
"""

        return report
